/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FindTeamRouteImport } from './routes/find-team'
import { Route as PostProjectRouteImport } from './routes/post-project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FindTeamRoute = FindTeamRouteImport.update({
  id: '/find-team',
  path: '/find-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PostProjectRoute = PostProjectRouteImport.update({
  id: '/post-project',
  path: '/post-project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-team': typeof FindTeamRoute
  '/post-project': typeof PostProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-team': typeof FindTeamRoute
  '/post-project': typeof PostProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-team': typeof FindTeamRoute
  '/post-project': typeof PostProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/find-team' | '/post-project'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-team' | '/post-project'
  id: '__root__' | '/' | '/find-team' | '/post-project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindTeamRoute: typeof FindTeamRoute
  PostProjectRoute: typeof PostProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-team': {
      id: '/find-team'
      path: '/find-team'
      fullPath: '/find-team'
      preLoaderRoute: typeof FindTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-project': {
      id: '/post-project'
      path: '/post-project'
      fullPath: '/post-project'
      preLoaderRoute: typeof PostProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindTeamRoute: FindTeamRoute,
  PostProjectRoute: PostProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
